/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char message[269];
	char name[10];
};
typedef struct message message;

struct chat_block {
	char block[900];
	int revision_number;
	int total_revisions;
};
typedef struct chat_block chat_block;

#define PROGRAM_WRITE 0x20000001
#define VERSION_WRITE 1

#if defined(__STDC__) || defined(__cplusplus)
#define write 0
extern  int * write_1(message *, CLIENT *);
extern  int * write_1_svc(message *, struct svc_req *);
#define getChat 1
extern  chat_block * getchat_1(int *, CLIENT *);
extern  chat_block * getchat_1_svc(int *, struct svc_req *);
extern int program_write_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define write 0
extern  int * write_1();
extern  int * write_1_svc();
#define getChat 1
extern  chat_block * getchat_1();
extern  chat_block * getchat_1_svc();
extern int program_write_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);
extern  bool_t xdr_chat_block (XDR *, chat_block*);

#else /* K&R C */
extern bool_t xdr_message ();
extern bool_t xdr_chat_block ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
