/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

int *
write_1_svc(message *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

chat_block *
getchat_1_svc(int *argp, struct svc_req *rqstp)
{
	static chat_block  result;

	/*
	 * insert server code here
	 */

	return &result;
}
